### ISSUE TITLE
Missing Service Name

### ISSUE THREAD

**Issue by mattdavis0351** [newrelic-experimental/gha-new-relic-exporter#29]
```2024-10-16 18:44:46,139 INFO [job_logger] [(unknown file):0] [trace_id=44fa8af10a437df32451d033533fd734 span_id=0edf4ce056e287cf resource.service.name= trace_sampled=True] - Cleaning up orphan processes```

appears the `resource.service.name` is not being populated and I'm unable to find the traces in New Relic even though the workflow run reports as successful.

Workflow file being used:

```yaml
name: new-relic-exporter

on:
  workflow_run:
    workflows: ['*']
    types: [completed] # defaults to run on every completed workflow run event

env:
  GHA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_PRD_LICENSE_KEY }}
  GHA_RUN_ID: ${{ github.event.workflow_run.id }}
  GHA_RUN_NAME: ${{ github.event.workflow_run.name }}
  GHA_DEBUG: "true"



jobs:
  new-relic-exporter:
    name: new-relic-exporter
    runs-on: self-hosted
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: new-relic-exporter
```
