### ISSUE TITLE
Unable to use new-relic-exporter github action if runner doesn't have docker cli installed

### ISSUE THREAD

**Issue by dusanslad** [newrelic-experimental/gha-new-relic-exporter#30]
Hi,
So I am struggling with using new-relic-exporter github action when the runner doesn't already have docker cli installed..
Each time I start my pipeline Build newrelic-experimental/gha-new-relic-exporter is being prioritized above other steps in the job:
![slika](https://github.com/user-attachments/assets/efce6e2b-615a-4b24-9626-e8abd7f7d3b3)

My job in workflow looks like this:
```
jobs:
  new-relic-exporter:
    name: new-relic-exporter
    runs-on: assentinc-ubuntu-runner
    if: ${{ always() }}
    steps: 
      # Step 1: Install and Set Up Docker CLI 
      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        

      # Step 2: Verify Docker Installation (explicit validation step)
      - name: Verify Docker Installation
        run: |
          docker --version || { echo "Docker CLI is not installed"; exit 1; }

      # Step 3: Run New Relic Exporter (only after Docker setup is verified)
      - name: Use New Relic Exporter
        uses: newrelic-experimental/gha-new-relic-exporter@latest   
```
        
  When I remove Step 3 (using New Relic Exporter Action) i have success pipeline:
  
![slika](https://github.com/user-attachments/assets/4ba3e26d-4638-4588-affd-0071da96feab)

And when add the step 3 i always get the same error from the 1st screenshot.. somehow action is being prioritized above the other steps, and I am not able to install docker cli to be able to use it for this action.

**Comment by dusanslad** [comment]
I have tried it as well but fails, as changes are not preserved between jobs:
![slika](https://github.com/user-attachments/assets/b1c89af7-bbe7-45e4-bec8-34f65a77468e)

**Comment by dpacheconr** [comment]
Each step is dependent on each other are executed in order that should have worked for you https://docs.github.com/en/actions/about-github-actions/understanding-github-actions#jobs 
But if using steps is not working and jobs don't automatically preserve data, I suggest try to use cache between the jobs
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow
I have not tried this but in theory should work
```
jobs:
  # Job 1: Install and set up Docker CLI
  setup-docker:
    name: Set Up Docker CLI
    runs-on: assentinc-ubuntu-runner
    steps:
      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Verify Docker Installation
        run: |
          docker --version || { echo "Docker CLI is not installed"; exit 1; }

      # Persist the Docker installation by creating an environment artifact.
      - name: Save Docker installation artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-cli
          path: /usr/bin/docker

  # Job 2: Use Docker and run New Relic Exporter
  new-relic-exporter:
    name: New Relic Exporter
    runs-on: assentinc-ubuntu-runner
    needs: setup-docker
    steps:
      # Restore the Docker installation from the artifact
      - name: Download Docker installation artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-cli

      - name: Verify Docker CLI is available
        run: |
          docker --version || { echo "Docker CLI not found after restoring"; exit 1; }

      - name: Use New Relic Exporter
        uses: newrelic-experimental/gha-new-relic-exporter@latest
```

**Comment by dusanslad** [comment]
still the same :(
2nd job doesn't even get to the step where it should actually download the installation artifact..
![slika](https://github.com/user-attachments/assets/591c274e-4fb9-4a5c-a4ef-802f10a8f42b)

**Comment by dpacheconr** [comment]
try using docker image instead of building it which is the default behaviour 

```
  new-relic-exporter:
    name: new-relic-exporter
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: new-relic-exporter
        uses: docker://ghcr.io/newrelic-experimental/gha-new-relic-exporter:latest
```
