### ISSUE TITLE
Not all pipeline jobs and steps are being exported to NR

### ISSUE THREAD

**Issue by dusanslad** [newrelic-experimental/gha-new-relic-exporter#32]
Hello,
I have ran gha-new-relic-exporter after one pipeline we use in our company which has multiple jobs and steps, but the last job and its steps are not being exported to the NR.
Here are the last few log lines of exporter:
```
2025-01-17T11:03:21.4868257Z Finished processing job -> Deploy to pre-prod / Deploy artist service to pre-prod / DB Permissions / post-status-to-slack
2025-01-17T11:03:21.4868522Z Finished processing Workflow -> Main Pipeline run id -> xxxxxx
2025-01-17T11:03:21.4868655Z All data exported to New Relic

```
And here is the pipeline itself, where we can see we had one more step "deploy to prod" which was executed succesfully but not being exported to NR:

![Image](https://github.com/user-attachments/assets/94ed0c7f-d357-4953-bf68-57dabda49b63)

Is there perhaps some log size limitation that is prevanting all the infromation to be exported?
After being exported this log is 8,548KB in size

**Comment by dusanslad** [comment]
Hi @dpacheconr  here is the workflow of new relic exporter:
```
name: new-relic-exporter

on:
  workflow_run:
    workflows: ['*']
    types: [completed] # defaults to run on every completed workflow run event

env:
  GHA_TOKEN: ${{ secrets.GH_TOKEN }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  GHA_RUN_ID: "${{ github.event.workflow_run.id }}"
  GHA_RUN_NAME: "${{ github.event.workflow_run.name }}"
  #GHA_DEBUG: ${{ secrets.GHA_DEBUG }} 
  #GHA_CUSTOM_ATTS: '{"mycustomattributea":"test", "mycustomattributeb":10, "mycustomattributec":"My custom attribute"}'


jobs:        
  new-relic-exporter:
    name: New Relic Exporter
    runs-on: codebuild-xxxx-ubuntu-runner-${{ github.run_id }}-${{ github.run_attempt }}
    if: ${{ always() }}
    steps:       
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Use New Relic Exporter
        uses: docker://ghcr.io/newrelic-experimental/gha-new-relic-exporter:latest

```
