### ISSUE TITLE
[bug] Nested reusable workflows are not logged correctly.

### ISSUE THREAD

**Issue by PBalsdon** [newrelic-experimental/gha-new-relic-exporter#39]
We have a job. That job uses a reusable workflow. We are getting an error 
```ERROR: Log file does not exist: Run reusable workflow  Deploy/1_Set up job.txt```

The workflow yaml looks like this:
```yaml
jobs:
  parent-job:
    name: Run reusable workflow
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: nonprod
```
And the name of reusable-workflow is `Deploy`.

With some investigation, it seems the log exporter is looking for a file path:
`{parent_job_name}  {reusable_workflow_name}/{step_number}_{step_name}.txt`

However, upon downloading the zip archive of the workflow in question, it seems that the file path of the logs in question is actually of the form 
`{parent_job_name} _ {reusable_workflow_name}/{step_number}_{step_name}.txt`

There appears to be a bug in the string manipulations when looking for the log file for a step.
