### ISSUE TITLE
exporter failing when set the type attribute on the workflow_run to [requested]

### ISSUE THREAD

**Issue by butchcarpio** [newrelic-experimental/gha-new-relic-exporter#9]
i wanted to create an alert for workflow jobs that are not picked up by any runner. i am thinking of setting a threshold time for the nr exporter run then when it hits the threshold, it will send an alert stating one workflow is in "waiting to pickup by a runner".
i am getting below error when i change the workflow_run > types to [requested]

```
on:
  workflow_dispatch:
  workflow_run:
    workflows: ['*']
    types: [requested]
```

![image](https://github.com/newrelic-experimental/gha-new-relic-exporter/assets/91664381/ecfd5598-5e0e-436b-af6a-e070418a33fa)
